getPromiseState
This was a review of the getPromiseState use. Do not use only for the reason
of running an async function. However, it must be used when such a function is
really returning a value; getPromiseState should else be avoided, with a distinct
exception: When the template call is made like mocking plain text it must be used
in order to avoid the textified printout of the 'promise object'.

Remains the cleaning up of commented-out code lines, searh for getPromiseState!